# Generated by Django 5.2.9 on 2025-12-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='page',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
